### ISSUE TITLE
Switch to lazyledger-core instead of tendermint

### ISSUE THREAD

**Issue by liamsi** [lazyledger/cosmos-sdk#2] opened 2021-01-04 18:47 UTC
Ensure that this fork uses lazyledger-core instead of tendermint as we will make use of some modifications of ll-core.

This probably means to search and replace go-imports. If a less invasive approach works that's even better (e.g. the [replace directive](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive)).

**Comment by evan-forbes** [comment] 2021-01-12 18:22
I figured I'd post my progress here and see if anyone can find something obvious while I continue to debug. I'm using the [evan/replace-tendermint](https://github.com/lazyledger/cosmos-sdk/tree/evan/replace-tendermint) branch, where I have manually replaced tendermint with lazyledger-core, updated the tendermint related proto files, and made a few minor compatibility changes to allow things to compile with the latest master branch of the sdk and lazyledger-core. Any ideas on what to try would be greatly appreciated. 

There are still nine tests that won't pass, but I think some are caused by the same issue. Here are the tests and their error, along with the [full output of `make test`](https://drive.google.com/file/d/1mbB8wnWeiRHdYcHdB_N5waqS22r_kMZO/view?usp=sharing)

TestInterceptConfigsPreRunHandlerReadsConfigToml - DBPath was not set from config.toml

TestInterceptConfigsPreRunHandlerDoesNotMixConfigFiles - DBPath was not set from config.toml

TestIntegrationTestSuite/TestGetCmdQueryAnnualProvisions/json_output - panic message redacted to hide potentially sensitive system info: panic

TestIntegrationTestSuite/TestGetCmdQueryAnnualProvisions/text_output - panic message redacted to hide potentially sensitive system info: panic

TestIntegrationTestSuite/TestGetCmdQueryInflation/json_output- panic message redacted to hide potentially sensitive system info: panic

TestIntegrationTestSuite/TestGetCmdQueryInflation/text_output - panic message redacted to hide potentially sensitive system info: panic

TestMintTestSuite/TestGRPCParams - test panicked: invalid Go type types.Dec for field cosmos.mint.v1beta1.QueryInflationResponse.inflation

TestIntegrationTestSuite/TestQueryGRPC/gRPC_request_inflation - Received unexpected error: unknown field "details" in types.QueryInflationResponse
  
TestIntegrationTestSuite/TestQueryGRPC/gRPC_request_annual_provisions - Received unexpected error: unknown field "details" in types.QueryAnnualProvisionsResponse


The output also repeats this message a few times, which I think *might* be because the cosmos-sdk is using the cosmos/iavl, which, as previously mentioned, has dependencies for tendermint, which also caries an extra copy of all the protof files in lazyledger-core. I'm going to try changing the proto package declarations for lazyledger-core next.
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.PublicKey
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.Proof
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ValueOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.DominoOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ProofOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ProofOps

**Comment by liamsi** [comment] 2021-01-13 17:37
Is there a branch I can checkout?

**Comment by evan-forbes** [comment] 2021-01-13 18:19
yeah 
> I'm using the [evan/replace-tendermint](https://github.com/lazyledger/cosmos-sdk/tree/evan/replace-tendermint) branch

**Comment by evan-forbes** [comment] 2021-01-14 04:22
So good (maybe bad...) news. After some more digging, all the remaining errors are due to the same thing. For some reason, protobuf is not recognizing the custom type found in two of the x/mint module's QueryResponse types [Inflation](https://github.com/cosmos/cosmos-sdk/blob/2a2c2ec009c6087f4536ec01e497b256523969a1/proto/cosmos/mint/v1beta1/query.proto#L42) and [AnnualProvisions](https://github.com/cosmos/cosmos-sdk/blob/2a2c2ec009c6087f4536ec01e497b256523969a1/proto/cosmos/mint/v1beta1/query.proto#L53). The weird thing is that [this custom type](https://github.com/cosmos/cosmos-sdk/blob/2a2c2ec009c6087f4536ec01e497b256523969a1/types/decimal.go#L17) is used in many other protobuf message types, including the mint module's own [Params](https://github.com/cosmos/cosmos-sdk/blob/2a2c2ec009c6087f4536ec01e497b256523969a1/proto/cosmos/mint/v1beta1/mint.proto#L22) message, which does not have same issue as the two mentioned message types.

**Comment by adlerjohn** [comment] 2021-01-14 04:26
Can you post the actual error? I might want to look into this since I've had to wrestle with protobuf before.

**Comment by evan-forbes** [comment] 2021-01-14 04:28
```invalid Go type types.Dec for field cosmos.mint.v1beta1.QueryAnnualProvisionsResponse.annual_provisions: panic [cosmos/cosmos-sdk/baseapp/abci.go:395]```

**Comment by evan-forbes** [comment] 2021-01-15 04:27
Just an update and personal notes on this sneaky bug:
The panic is occurring when protobuf is marshalling the response [here](https://github.com/protocolbuffers/protobuf-go/blob/3f7a61f89bb6813f89d981d1870ed68da0b3c3f1/internal/impl/convert.go#L90). The `types.Dec` type is being reflected as `bytes`, which I'm fairly certain is wrong. The weirdest thing is that I still can't figure out why switching to ll-core causes this bug. So far, all the code that has to do with the bug is contained in the cosmos-sdk. I have also been unable to recreate the bug outside of this context. Those things make me think it could be another weird dependency bug, especially considering the multiple versions of `google.golang.org/protobuf`, `github.com/gogo/protobuf`, `github.com/golang/protobuf` that are required in the dependency tree. If that's true, updating the dependency graph with be more difficult than it was before, where we could just remove one of the three protobuf libraries, like we did with iavl. Unlike last time, everything compiles, so I'm confident we can pinpoint exactly what is causing this nasty bug, and finally remedy it.

Tomorrow, I'll give another go at recreating the bug outside of this context, and then I think I'm going to try [#138](https://github.com/lazyledger/lazyledger-core/issues/138) porting changes from v0.34.2 to lazyledger-core, and see if that makes a difference. 

PS: after diving through the layers of reflection in protobuf, I am now **firmly** in the "go needs generics" boat.

**Comment by liamsi** [comment] 2021-01-15 13:53
> Tomorrow, I'll give another go at recreating the bug outside of this context, and then I think I'm going to try #138 porting changes from v0.34.2 to lazyledger-core, and see if that makes a difference.

Yeah, it's probably a good idea if ll-core is on par with the release that version of the SDK uses (independent of if this is causing the described problems or not; but it's likely related).

**Comment by evan-forbes** [comment] 2021-01-16 01:39
Huge thank you to @liamsi for finding the source of the bugs, and to everyone else that took the time to help me. It was a dependency issue, although I tried different versions of protobuf and gogo/protobuf, I wasn't changing versions of grpc, which was the problem dependency that got auto updated by switching to lazyledger-core. Since then, lazyledger-core's version of grpc has been [downgraded](https://github.com/lazyledger/lazyledger-core/pull/143), and a [PR](https://github.com/lazyledger/cosmos-sdk/pull/13) submitted to close this issue.

I guess I also owe an apology to protobuf, for all the curses I threw its way while I tried to fix what I thought was a sneaky marshalling bug.

We still might want to look into a fix for the duplicate registry of protobuf types, but that's another [issue](https://github.com/lazyledger/lazyledger-core/issues/145).

**Closed** 2021-01-21 15:24 UTC
Labels: P:High
